#!/bin/sh

function ip() {
	if command ip "$@"; then return 0; fi

	if command ip "$@" 2>&1 | grep -qP "Operation not permitted"; then
		printf "%s\n" "$(tput smso)$(tput setaf 1)sudo: privilege escalation required$(tput sgr0)"
		sudo "ip" "$@"
	fi
}
